-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Event"."EventStore"
(
    "Id" bigint NOT NULL,
    "EventVersion" bigint NOT NULL,
    "EventType" text COLLATE pg_catalog."default",
    "AggregateId" bigint NOT NULL,
    "AggregateType" text COLLATE pg_catalog."default",
    "EventData" text COLLATE pg_catalog."default",
    "PublishTime" timestamp without time zone NOT NULL,
    "PublishStatus" integer NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_EventStore" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
END;