-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Identifier"."DeviceIdentifiers"
(
    "Id" bigint NOT NULL,
    "EntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    "Kind" integer NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Value" text COLLATE pg_catalog."default",
    "Key" bigint NOT NULL,
    CONSTRAINT "PK_DeviceIdentifiers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Identifier"."UserIdentifiers"
(
    "Id" bigint NOT NULL,
    "EntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    "Kind" integer NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Value" text COLLATE pg_catalog."default",
    "Key" bigint NOT NULL,
    CONSTRAINT "PK_UserIdentifiers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Addresses"
(
    "Id" bigint NOT NULL,
    "CityName" character varying COLLATE pg_catalog."default" NOT NULL,
    "StreetName" character varying COLLATE pg_catalog."default" NOT NULL,
    "BuildingNumber" character varying COLLATE pg_catalog."default",
    "ApartmentNumber" character varying COLLATE pg_catalog."default" NOT NULL,
    "Postcode" character varying COLLATE pg_catalog."default" NOT NULL,
    "Notices" character varying COLLATE pg_catalog."default",
    "Type" integer NOT NULL,
    "CountryId" bigint,
    "StateId" bigint,
    "ContactId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Attributes"
(
    "Id" bigint NOT NULL,
    "Key" character varying COLLATE pg_catalog."default" NOT NULL,
    "Value" character varying COLLATE pg_catalog."default" NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Attributes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Configurations"
(
    "Id" bigint NOT NULL,
    "OrganizationId" bigint,
    "TeamId" bigint,
    "ConfigurationId" bigint,
    "UserId" bigint,
    "ShiftLength" integer NOT NULL,
    "HasEmailNotifications" boolean NOT NULL,
    "HasPushNotifications" boolean NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Configurations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Contacts"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Type" integer NOT NULL,
    "Email" text COLLATE pg_catalog."default",
    "PhoneType" integer NOT NULL,
    "PhoneNumber" text COLLATE pg_catalog."default",
    "Notices" text COLLATE pg_catalog."default",
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Countries"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Code" text COLLATE pg_catalog."default",
    "Continent" text COLLATE pg_catalog."default",
    "TimeZone" text COLLATE pg_catalog."default",
    "CurrencyId" bigint,
    "LanguageId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."CountryLanguages"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Code" text COLLATE pg_catalog."default",
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_CountryLanguages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."CountryStates"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Code" text COLLATE pg_catalog."default",
    "TimeZone" text COLLATE pg_catalog."default",
    "CountryId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_CountryStates" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Currencies"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Code" text COLLATE pg_catalog."default",
    "Rate" double precision NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."DeviceSessions"
(
    "Id" bigint NOT NULL,
    "DeviceId" bigint,
    "Port" integer NOT NULL,
    "MACAddress" text COLLATE pg_catalog."default",
    "ConnectedOn" timestamp without time zone NOT NULL,
    "DurationTime" integer NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_DeviceSessions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Devices"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "SerialNumber" text COLLATE pg_catalog."default",
    "HostName" text COLLATE pg_catalog."default",
    "Model" text COLLATE pg_catalog."default",
    "SystemInfo" text COLLATE pg_catalog."default",
    "SystemVersion" text COLLATE pg_catalog."default",
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Devices" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Organizations"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "ShortName" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "Notices" text COLLATE pg_catalog."default",
    "ConfigurationId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Personals"
(
    "Id" bigint NOT NULL,
    "Title" text COLLATE pg_catalog."default",
    "Profession" text COLLATE pg_catalog."default",
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" character varying COLLATE pg_catalog."default",
    "FirstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "SecondName" text COLLATE pg_catalog."default",
    "LastName" character varying COLLATE pg_catalog."default" NOT NULL,
    "FullName" character varying COLLATE pg_catalog."default",
    "Birthdate" timestamp without time zone NOT NULL,
    "Age" integer NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Personals" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Plans"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "Interval" interval NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Plans" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Schedules"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "Interval" interval NOT NULL,
    "OrganizationId" bigint,
    "TeamId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Schedules" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."ShiftRatings"
(
    "Id" bigint NOT NULL,
    "Rank" integer NOT NULL,
    "Weekly" integer NOT NULL,
    "Monthly" integer NOT NULL,
    "Yearly" integer NOT NULL,
    "Weekends" integer NOT NULL,
    "Holidays" integer NOT NULL,
    "WorkCount" integer NOT NULL,
    "OffCount" integer NOT NULL,
    "FreeCount" integer NOT NULL,
    "UserId" bigint,
    "ShiftTypeId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftRatings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."ShiftRequests"
(
    "Id" bigint NOT NULL,
    "Reason" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "UserId" bigint,
    "RequestShiftId" bigint,
    "RequestedShiftId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftRequests" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."ShiftTypes"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "HoursLength" real NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Shifts"
(
    "Id" bigint NOT NULL,
    "OrganizationId" bigint,
    "TeamId" bigint,
    "UserId" bigint,
    "ShiftTypeId" bigint,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "Interval" interval NOT NULL,
    "RequestedShiftId" bigint,
    "WorkMode" integer NOT NULL,
    "HasRequests" boolean NOT NULL,
    "IsRequested" boolean NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Teams"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "ShortName" character varying COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "OrganizationId" bigint,
    "LeadershipId" bigint,
    "ConfigurationId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."UserRoles"
(
    "Id" bigint NOT NULL,
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    "Type" integer NOT NULL,
    "UserId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Local"."Users"
(
    "Id" bigint NOT NULL,
    "UserId" uuid NOT NULL,
    "UserName" character varying COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" character varying COLLATE pg_catalog."default",
    "PersonalId" bigint,
    "ConfigurationId" bigint,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Relation"."ConfigurationsToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ConfigurationsToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."OrganizationsToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_OrganizationsToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."OrganizationsToPlans"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_OrganizationsToPlans" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."OrganizationsToUsers"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_OrganizationsToUsers" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."PersonalsToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_PersonalsToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftTypesToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypesToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftTypesToOrganizations"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypesToOrganizations" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftTypesToPlans"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypesToPlans" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftTypesToTeams"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypesToTeams" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftTypesToUsers"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftTypesToUsers" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftsToPlans"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftsToPlans" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."ShiftsToSchedules"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_ShiftsToSchedules" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."TeamsToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_TeamsToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."TeamsToPlans"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_TeamsToPlans" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."UsersToAttributes"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UsersToAttributes" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."UsersToContacts"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UsersToContacts" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."UsersToDevices"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UsersToDevices" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."UsersToPlans"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UsersToPlans" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS "Relation"."UsersToTeams"
(
    "RightEntityId" bigint NOT NULL,
    "LeftEntityId" bigint NOT NULL,
    "OriginId" smallint NOT NULL,
    "OriginName" character varying(32) COLLATE pg_catalog."default",
    "Modified" timestamp without time zone NOT NULL,
    "Modifier" character varying(32) COLLATE pg_catalog."default",
    "Created" timestamp without time zone NOT NULL,
    "Creator" character varying(32) COLLATE pg_catalog."default",
    "Id" bigint NOT NULL,
    "Number" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Priority" smallint NOT NULL,
    "SerialCode" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "Label" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UsersToTeams" PRIMARY KEY ("LeftEntityId", "RightEntityId")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS "Identifier"."DeviceIdentifiers"
    ADD CONSTRAINT "FK_DeviceIdentifiers_Devices_EntityId" FOREIGN KEY ("EntityId")
    REFERENCES "Local"."Devices" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_DeviceIdentifiers_EntityId"
    ON "Identifier"."DeviceIdentifiers"("EntityId");


ALTER TABLE IF EXISTS "Identifier"."UserIdentifiers"
    ADD CONSTRAINT "FK_UserIdentifiers_Users_EntityId" FOREIGN KEY ("EntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_UserIdentifiers_EntityId"
    ON "Identifier"."UserIdentifiers"("EntityId");


ALTER TABLE IF EXISTS "Local"."Addresses"
    ADD CONSTRAINT "FK_Addresses_Contacts_ContactId" FOREIGN KEY ("ContactId")
    REFERENCES "Local"."Contacts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Addresses_ContactId"
    ON "Local"."Addresses"("ContactId");


ALTER TABLE IF EXISTS "Local"."Addresses"
    ADD CONSTRAINT "FK_Addresses_Countries_CountryId" FOREIGN KEY ("CountryId")
    REFERENCES "Local"."Countries" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Addresses_CountryId"
    ON "Local"."Addresses"("CountryId");


ALTER TABLE IF EXISTS "Local"."Addresses"
    ADD CONSTRAINT "FK_Addresses_CountryStates_StateId" FOREIGN KEY ("StateId")
    REFERENCES "Local"."CountryStates" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Addresses_StateId"
    ON "Local"."Addresses"("StateId");


ALTER TABLE IF EXISTS "Local"."Configurations"
    ADD CONSTRAINT "FK_Configurations_Organizations_ConfigurationId" FOREIGN KEY ("ConfigurationId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Configurations_ConfigurationId"
    ON "Local"."Configurations"("ConfigurationId");


ALTER TABLE IF EXISTS "Local"."Configurations"
    ADD CONSTRAINT "FK_Configurations_Teams_ConfigurationId" FOREIGN KEY ("ConfigurationId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Configurations_ConfigurationId"
    ON "Local"."Configurations"("ConfigurationId");


ALTER TABLE IF EXISTS "Local"."Configurations"
    ADD CONSTRAINT "FK_Configurations_Users_ConfigurationId" FOREIGN KEY ("ConfigurationId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Configurations_ConfigurationId"
    ON "Local"."Configurations"("ConfigurationId");


ALTER TABLE IF EXISTS "Local"."Countries"
    ADD CONSTRAINT "FK_Countries_CountryLanguages_LanguageId" FOREIGN KEY ("LanguageId")
    REFERENCES "Local"."CountryLanguages" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Countries_LanguageId"
    ON "Local"."Countries"("LanguageId");


ALTER TABLE IF EXISTS "Local"."Countries"
    ADD CONSTRAINT "FK_Countries_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId")
    REFERENCES "Local"."Currencies" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Countries_CurrencyId"
    ON "Local"."Countries"("CurrencyId");


ALTER TABLE IF EXISTS "Local"."CountryStates"
    ADD CONSTRAINT "FK_CountryStates_Countries_CountryId" FOREIGN KEY ("CountryId")
    REFERENCES "Local"."Countries" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_CountryStates_CountryId"
    ON "Local"."CountryStates"("CountryId");


ALTER TABLE IF EXISTS "Local"."DeviceSessions"
    ADD CONSTRAINT "FK_DeviceSessions_Devices_DeviceId" FOREIGN KEY ("DeviceId")
    REFERENCES "Local"."Devices" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_DeviceSessions_DeviceId"
    ON "Local"."DeviceSessions"("DeviceId");


ALTER TABLE IF EXISTS "Local"."Schedules"
    ADD CONSTRAINT "FK_Schedules_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Schedules_OrganizationId"
    ON "Local"."Schedules"("OrganizationId");


ALTER TABLE IF EXISTS "Local"."Schedules"
    ADD CONSTRAINT "FK_Schedules_Teams_TeamId" FOREIGN KEY ("TeamId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Schedules_TeamId"
    ON "Local"."Schedules"("TeamId");


ALTER TABLE IF EXISTS "Local"."ShiftRatings"
    ADD CONSTRAINT "FK_ShiftRatings_ShiftTypes_ShiftTypeId" FOREIGN KEY ("ShiftTypeId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_ShiftRatings_ShiftTypeId"
    ON "Local"."ShiftRatings"("ShiftTypeId");


ALTER TABLE IF EXISTS "Local"."ShiftRatings"
    ADD CONSTRAINT "FK_ShiftRatings_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_ShiftRatings_UserId"
    ON "Local"."ShiftRatings"("UserId");


ALTER TABLE IF EXISTS "Local"."ShiftRequests"
    ADD CONSTRAINT "FK_ShiftRequests_Shifts_RequestShiftId" FOREIGN KEY ("RequestShiftId")
    REFERENCES "Local"."Shifts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_ShiftRequests_RequestShiftId"
    ON "Local"."ShiftRequests"("RequestShiftId");


ALTER TABLE IF EXISTS "Local"."ShiftRequests"
    ADD CONSTRAINT "FK_ShiftRequests_Shifts_RequestedShiftId" FOREIGN KEY ("RequestedShiftId")
    REFERENCES "Local"."Shifts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_ShiftRequests_RequestedShiftId"
    ON "Local"."ShiftRequests"("RequestedShiftId");


ALTER TABLE IF EXISTS "Local"."ShiftRequests"
    ADD CONSTRAINT "FK_ShiftRequests_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_ShiftRequests_UserId"
    ON "Local"."ShiftRequests"("UserId");


ALTER TABLE IF EXISTS "Local"."Shifts"
    ADD CONSTRAINT "FK_Shifts_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Shifts_OrganizationId"
    ON "Local"."Shifts"("OrganizationId");


ALTER TABLE IF EXISTS "Local"."Shifts"
    ADD CONSTRAINT "FK_Shifts_ShiftTypes_ShiftTypeId" FOREIGN KEY ("ShiftTypeId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Shifts_ShiftTypeId"
    ON "Local"."Shifts"("ShiftTypeId");


ALTER TABLE IF EXISTS "Local"."Shifts"
    ADD CONSTRAINT "FK_Shifts_Teams_TeamId" FOREIGN KEY ("TeamId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Shifts_TeamId"
    ON "Local"."Shifts"("TeamId");


ALTER TABLE IF EXISTS "Local"."Shifts"
    ADD CONSTRAINT "FK_Shifts_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Shifts_UserId"
    ON "Local"."Shifts"("UserId");


ALTER TABLE IF EXISTS "Local"."Teams"
    ADD CONSTRAINT "FK_Teams_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Teams_OrganizationId"
    ON "Local"."Teams"("OrganizationId");


ALTER TABLE IF EXISTS "Local"."Teams"
    ADD CONSTRAINT "FK_Teams_Users_LeadershipId" FOREIGN KEY ("LeadershipId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Teams_LeadershipId"
    ON "Local"."Teams"("LeadershipId");


ALTER TABLE IF EXISTS "Local"."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_UserRoles_UserId"
    ON "Local"."UserRoles"("UserId");


ALTER TABLE IF EXISTS "Local"."Users"
    ADD CONSTRAINT "FK_Users_Personals_PersonalId" FOREIGN KEY ("PersonalId")
    REFERENCES "Local"."Personals" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Users_PersonalId"
    ON "Local"."Users"("PersonalId");


ALTER TABLE IF EXISTS "Relation"."ConfigurationsToAttributes"
    ADD CONSTRAINT "FK_ConfigurationsToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ConfigurationsToAttributes_RightEntityId"
    ON "Relation"."ConfigurationsToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ConfigurationsToAttributes"
    ADD CONSTRAINT "FK_ConfigurationsToAttributes_Configurations_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Configurations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."OrganizationsToAttributes"
    ADD CONSTRAINT "FK_OrganizationsToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_OrganizationsToAttributes_RightEntityId"
    ON "Relation"."OrganizationsToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."OrganizationsToAttributes"
    ADD CONSTRAINT "FK_OrganizationsToAttributes_Organizations_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."OrganizationsToPlans"
    ADD CONSTRAINT "FK_OrganizationsToPlans_Organizations_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."OrganizationsToPlans"
    ADD CONSTRAINT "FK_OrganizationsToPlans_Plans_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Plans" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_OrganizationsToPlans_RightEntityId"
    ON "Relation"."OrganizationsToPlans"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."OrganizationsToUsers"
    ADD CONSTRAINT "FK_OrganizationsToUsers_Organizations_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."OrganizationsToUsers"
    ADD CONSTRAINT "FK_OrganizationsToUsers_Users_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_OrganizationsToUsers_RightEntityId"
    ON "Relation"."OrganizationsToUsers"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."PersonalsToAttributes"
    ADD CONSTRAINT "FK_PersonalsToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_PersonalsToAttributes_RightEntityId"
    ON "Relation"."PersonalsToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."PersonalsToAttributes"
    ADD CONSTRAINT "FK_PersonalsToAttributes_Personals_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Personals" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToAttributes"
    ADD CONSTRAINT "FK_ShiftTypesToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftTypesToAttributes_RightEntityId"
    ON "Relation"."ShiftTypesToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToAttributes"
    ADD CONSTRAINT "FK_ShiftTypesToAttributes_ShiftTypes_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToOrganizations"
    ADD CONSTRAINT "FK_ShiftTypesToOrganizations_Organizations_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Organizations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftTypesToOrganizations_RightEntityId"
    ON "Relation"."ShiftTypesToOrganizations"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToOrganizations"
    ADD CONSTRAINT "FK_ShiftTypesToOrganizations_ShiftTypes_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToPlans"
    ADD CONSTRAINT "FK_ShiftTypesToPlans_Plans_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Plans" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftTypesToPlans_RightEntityId"
    ON "Relation"."ShiftTypesToPlans"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToPlans"
    ADD CONSTRAINT "FK_ShiftTypesToPlans_ShiftTypes_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToTeams"
    ADD CONSTRAINT "FK_ShiftTypesToTeams_ShiftTypes_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToTeams"
    ADD CONSTRAINT "FK_ShiftTypesToTeams_Teams_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftTypesToTeams_RightEntityId"
    ON "Relation"."ShiftTypesToTeams"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToUsers"
    ADD CONSTRAINT "FK_ShiftTypesToUsers_ShiftTypes_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."ShiftTypes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftTypesToUsers"
    ADD CONSTRAINT "FK_ShiftTypesToUsers_Users_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftTypesToUsers_RightEntityId"
    ON "Relation"."ShiftTypesToUsers"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftsToPlans"
    ADD CONSTRAINT "FK_ShiftsToPlans_Plans_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Plans" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftsToPlans_RightEntityId"
    ON "Relation"."ShiftsToPlans"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftsToPlans"
    ADD CONSTRAINT "FK_ShiftsToPlans_Shifts_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Shifts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."ShiftsToSchedules"
    ADD CONSTRAINT "FK_ShiftsToSchedules_Schedules_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Schedules" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ShiftsToSchedules_RightEntityId"
    ON "Relation"."ShiftsToSchedules"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."ShiftsToSchedules"
    ADD CONSTRAINT "FK_ShiftsToSchedules_Shifts_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Shifts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."TeamsToAttributes"
    ADD CONSTRAINT "FK_TeamsToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TeamsToAttributes_RightEntityId"
    ON "Relation"."TeamsToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."TeamsToAttributes"
    ADD CONSTRAINT "FK_TeamsToAttributes_Teams_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."TeamsToPlans"
    ADD CONSTRAINT "FK_TeamsToPlans_Plans_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Plans" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TeamsToPlans_RightEntityId"
    ON "Relation"."TeamsToPlans"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."TeamsToPlans"
    ADD CONSTRAINT "FK_TeamsToPlans_Teams_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."UsersToAttributes"
    ADD CONSTRAINT "FK_UsersToAttributes_Attributes_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Attributes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_UsersToAttributes_RightEntityId"
    ON "Relation"."UsersToAttributes"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."UsersToAttributes"
    ADD CONSTRAINT "FK_UsersToAttributes_Users_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."UsersToContacts"
    ADD CONSTRAINT "FK_UsersToContacts_Contacts_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Contacts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_UsersToContacts_RightEntityId"
    ON "Relation"."UsersToContacts"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."UsersToContacts"
    ADD CONSTRAINT "FK_UsersToContacts_Users_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."UsersToDevices"
    ADD CONSTRAINT "FK_UsersToDevices_Devices_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Devices" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_UsersToDevices_RightEntityId"
    ON "Relation"."UsersToDevices"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."UsersToDevices"
    ADD CONSTRAINT "FK_UsersToDevices_Users_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."UsersToPlans"
    ADD CONSTRAINT "FK_UsersToPlans_Plans_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Plans" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_UsersToPlans_RightEntityId"
    ON "Relation"."UsersToPlans"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."UsersToPlans"
    ADD CONSTRAINT "FK_UsersToPlans_Users_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS "Relation"."UsersToTeams"
    ADD CONSTRAINT "FK_UsersToTeams_Teams_RightEntityId" FOREIGN KEY ("RightEntityId")
    REFERENCES "Local"."Teams" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_UsersToTeams_RightEntityId"
    ON "Relation"."UsersToTeams"("RightEntityId");


ALTER TABLE IF EXISTS "Relation"."UsersToTeams"
    ADD CONSTRAINT "FK_UsersToTeams_Users_LeftEntityId" FOREIGN KEY ("LeftEntityId")
    REFERENCES "Local"."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;