name: Auto PR test(bot)

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  run_test:
    name: run test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Test
        run: |
          dotnet test test/UnitTest -c Release --collect:"XPlat Code Coverage"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
